package net.dasherz.wifiwolf.common.util;

public enum ValidationCode {
	VALID, ERROR_ID_PASSWORD, ERROR_VERIFY_CODE_EXPIRED, ERROR_VERIFY_CODE_NOT_EXIST, ERROR_VERIFY_CODE_WRONG, ERROR_SYSTEM_AUTH_TYPE, ERROR_PHONE_NUMBER_FORMAT, ERROR_WIFI_DISABLED, ERROR_USER_EXIST;

}
